### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ghost** [clayrisser/react-native-ignore-warnings#3]
getting couldn't find preset "env" relative to directory

**Comment by clayrisser** [comment]
Could you copy and paste the full stack trace?

**Comment by ghost** [comment]
I'm using create-react-native-app.  I go to the project folder and npm install --save react-native-ignore-warnings  when I do this is written to the console.log:

    λ npm install --save react-native-ignore-warnings
    todo@0.1.0 d:\testbed\react-native\todo
    `-- react-native-ignore-warnings@0.1.1
      `-- ignore-warnings@0.1.0

    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm@2.2.8 
    (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-linux-arm):
     npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-l 
     linux-arm@2.2.8: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
     npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-x64@2.2.8 
     (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-darwin-x64):
     npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin- 
     darwin-x64@2.2.8: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
     npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-ia32@2.2.8 
     (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-freebsd-ia32):
     npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin- 
     freebsd-ia32@2.2.8: wanted {"os":"freebsd","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-x64@2.2.8 
    (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-linux-x64): 
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin- 
    linux-x64@2.2.8: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-sunos-x64@2.2.8 
    (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-sunos-x64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin- 
    sunos-x64@2.2.8: wanted {"os":"sunos","arch":"x64"} (current: {"os":"win32","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-x64@2.2.8 
    (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-freebsd-x64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin- 
    freebsd-x64@2.2.8: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-ia32@2.2.8 
    (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-linux-ia32):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin- 
    linux-ia32@2.2.8: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-ia32@2.2.8 
    (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-darwin-ia32):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin- 
    darwin-ia32@2.2.8: wanted {"os":"darwin","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm64@2.2.8 
    (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-linux-arm64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin- 
    linux-arm64@2.2.8: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-ia32@2.2.8-beta.1 
    (node_modules\@expo\ngrok-bin\node_modules\@expo\ngrok-bin-win32-ia32):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin- 
    win32-ia32@2.2.8-beta.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 
    (node_modules\sane\node_modules\fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: 
    wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
    npm WARN @babel/plugin-check-constants@7.0.0-beta.38 requires a peer of @babel/core@7.0.0- 
    beta.38 but none was installed.
    npm WARN react-native-maps@0.20.1 requires a peer of react@^16.0 but none was installed.
    npm WARN react-test-renderer@16.3.1 requires a peer of react@^16.0.0 but none was installed.
    npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was 
    installed.
    npm WARN react-native-gesture-handler@1.0.0-alpha.41 requires a peer of react@> 15.0.0 but none 
    was installed.
    npm WARN react-native-maps@0.20.1 requires a peer of react@^16.0 but none was installed.

Then on the first line of my app.js file (I don't have an index.js) I import ignoreWarnings from 'react-native-ignore-warnings'; and after my other imports I add:

    ignoreWarnings(['Warning:'])  I also tried   ignoreWarnings('Warning:')

then on my iphone I get the following:

    d:\testbed\react-native\todo\node_modules\react-native-ignore-warnings\lib\index.js: Couldn't find 
    preset "env" relative to directory "d:\\testbed\\react-native\\todo\\node_modules\\react-native- 
    ignore-warnings"

    ABI25_0_0RCTFBQuickPerformanceLoggerConfigureHooks
    ABI26_0_0RCTFBQuickPerformanceLoggerConfigureHooks
    <redacted>
    <redacted>
    <redacted>
    <redacted>
    <redacted>
    CFRunLoopRunSpecific
    GSEventRunModal
    UIApplicationMain
    Exponent
    <redacted>

And this is written to the console.log:

     Failed building JavaScript bundle
    13:33:15: Failed building JavaScript bundle
    13:33:32: Failed building JavaScript bundle
    13:33:33: Failed building JavaScript bundle
    13:34:06: Failed building JavaScript bundle
    13:34:07: Failed building JavaScript bundle
    13:34:11: Failed building JavaScript bundle
    13:34:11: Failed building JavaScript bundle
    13:34:21: Failed building JavaScript bundle
    13:34:22: Failed building JavaScript bundle
    Building JavaScript bundle [===================================================================================== ] 99%

I reloaded several times but it stops at 99%

**Comment by clayrisser** [comment]
I think the error is related to your babel config

**Comment by clayrisser** [comment]
Can you send me your babel config?

**Comment by ghost** [comment]
I currently have react-native-ignore-warnings uninstalled.  My .babelrc file is:

{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}

Sent from Mail for Windows 10

**Comment by clayrisser** [comment]
Try installing the following . . .

```sh
npm install --save-dev babel-preset-env
```

**Comment by ghost** [comment]
Still doesn’t work. This is new error message:

d:\testbed\react-native\todo\node_modules\react-native-ignore-warnings\lib\index.js: Couldn't find preset "stage-2" relative to directory "d:\\testbed\\react-native\\todo\\node_modules\\react-native-ignore-warnings"

ABI25_0_0RCTFBQuickPerformanceLoggerConfigureHooks
ABI26_0_0RCTFBQuickPerformanceLoggerConfigureHooks
<redacted>
<redacted>
<redacted>
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
Exponent
<redacted>

**Comment by clayrisser** [comment]
Nice, that means it fixed the error :)
Now run . . .

```sh
npm install --save-dev babel-preset-stage-2
```

**Comment by clayrisser** [comment]
I think I might just move those modules into the regular deps to prevent users from needing to install them.

**Comment by ghost** [comment]
I’m sure there are a lot of users like me who are just learning this stuff.  Your help is greatly appreciated.  There’s noway I would have been able to solve this on my own


Sent from Mail for Windows 10

**Comment by ghost** [comment]
This doesn’t seem to exist.

λ npm install --save-dev babel-plugin-stage-2
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/babel-plugin-stage-2
npm ERR! 404
npm ERR! 404  'babel-plugin-stage-2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saltydog\AppData\Roaming\npm-cache\_logs\2018-04-14T22_25_56_519Z-debug.log

Sent from Mail for Windows 10

**Comment by clayrisser** [comment]
Oh, I'm sorry, it's babel-preset-stage-2

```sh
npm install --save-dev babel-preset-stage-2
```

**Comment by ghost** [comment]
Awesome, working like a charm.  Thanks again.

Sent from Mail for Windows 10

**Comment by ghost** [comment]
we can close this out
