### ISSUE TITLE
Is there a way to globally install

### ISSUE THREAD

**Issue by ghost** [clayrisser/react-native-ignore-warnings#4]
Hi, I added the -g option to react-native-ignore-warnings , babel-preset-env and babel-preset-stage-2.  When I run I get unable to resolve module 'react-native-ignore-warnings.  Is there a way to install the package globally?

**Comment by clayrisser** [comment]
Yes, you would need to link the packages after installing them globally.

```sh
npm install -g react-native-ignore-warnings babel-preset-env and babel-preset-stage-2
npm link react-native-ignore-warnings babel-preset-env and babel-preset-stage-2
```

**Comment by ghost** [comment]
I have a react-native folder that contains a folder for each of my projects.  I npm install -g react-native-ignore-warnings babel-preset-env babel-preset-stage-2 from that directory and then issue the link command.  I get:

npm run link react-native-ignore-warnings babel-preset-env babel-preset-stage-2
npm ERR! path d:\testbed\react-native\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'd:\testbed\react-native\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saltydog\AppData\Roaming\npm-cache\_logs\2018-04-16T18_12_21_732Z-debug.log

when I run the link command from a project root folder I get:

d:\testbed\react-native\lifecycle
λ npm run link react-native-ignore-warnings babel-preset-env babel-preset-stage-2
npm ERR! missing script: link

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saltydog\AppData\Roaming\npm-cache\_logs\2018-04-16T18_15_24_605Z-debug.log


Sent from Mail for Windows 10

**Comment by clayrisser** [comment]
Sorry, `npm link` not `npm run link`

**Comment by clayrisser** [comment]
I fixed it in the previous comment

**Comment by ghost** [comment]
Sorry to keep bothering you.  I really do appreciate your help.  Running the link command generates:

λ npm link react-native-ignore-warnings babel-preset-env babel-preset-stage-2 @rss81
npm ERR! addLocal Could not install d:\testbed\react-native\@rss81
d:\testbed\react-native\node_modules\react-native-ignore-warnings -> C:\Users\saltydog\AppData\Roaming\npm\node_modules\react-native-ignore-warnings
d:\testbed\react-native\node_modules\babel-preset-env -> C:\Users\saltydog\AppData\Roaming\npm\node_modules\babel-preset-env
d:\testbed\react-native\node_modules\babel-preset-stage-2 -> C:\Users\saltydog\AppData\Roaming\npm\node_modules\babel-preset-stage-2
npm ERR! path d:\testbed\react-native\@rss81
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'd:\testbed\react-native\@rss81'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saltydog\AppData\Roaming\npm-cache\_logs\2018-04-16T18_37_20_754Z-debug.log

Sent from Mail for Windows 10

**Comment by clayrisser** [comment]
That's because you ran  . . .

```sh
npm link react-native-ignore-warnings babel-preset-env babel-preset-stage-2 @rss81
```

You're supposed to run  . . .

```sh
npm link react-native-ignore-warnings babel-preset-env babel-preset-stage-2
```

**Comment by clayrisser** [comment]
Make sure what you copy and paste is actually correct, it can help prevent errors.

**Comment by clayrisser** [comment]
Also, read the error message. It's pretty clear what the issue is.

```sh
Could not install d:\testbed\react-native\@rss81
```

**Comment by ghost** [comment]
Thanks, that was dumb on my part.  With the right command I now get:

Unable to resolve react-native-ignore-warnings" from "./d:\\testbed\\react-native\\lifecycle\\App.js"
15:29:30: Failed building JavaScript bundle
15:29:32: Unable to resolve react-native-ignore-warnings" from "./d:\\testbed\\react-native\\lifecycle\\App.js"
15:29:32: Failed building JavaScript bundle

Sent from Mail for Windows 10

**Comment by clayrisser** [comment]
You globally installed it and you linked it?

Try running node in your app folder . . .

```sh
node
```

Then require react-native-ignore-warnings and `console.log` it

```js
console.log(require('react-native-ignore-warnings'))
```

**Comment by ghost** [comment]
I think this is just not going to work.  I had to install react-native globally.  Then when I ran node the console.log gave me
> console.log(require('react-native-ignore-warnings'))
{ default: [Function] }
undefined
>

I reran the link command, I recreated the project directory with create-react-native-app and when I run I get Unable to resolve module react-native-ignore-warnings.  Module does not exist in the module map.

Sent from Mail for Windows 10

**Comment by clayrisser** [comment]
Ok, yeah that means it's loading the module. React is possibly incapable of loading it globally. If you want to filter the module from your build dependencies, install it as a dev dependency. Just make sure to only import the module in development mode.

**Comment by clayrisser** [comment]
```sh
npm install --save-dev react-native-ignore-warnings
export NODE_ENV=development
```

```js
if (process.env.NODE_ENV === 'development') {
  const ignoreWarnings = require('react-native-ignore-warnings');
  ignoreWarnings([
    'Watch your six',
    'Mind the gap',
    'Beware the ides of March'
  ]);
}
```

**Comment by ghost** [comment]
Ok, thanks again for all your help.  I notice your beerpay link is not working 😊 

Sent from Mail for Windows 10
