### ISSUE TITLE
YellowBox has been replaced with LogBox

### ISSUE THREAD

**Issue by natemartins** [clayrisser/react-native-ignore-warnings#5]
YellowBox has been replaced with LogBox in React Native. Hence, it shows the warning in the title of this issue.

Fix: Import LogBox from react-native instead of YellowBox

**Comment by clayrisser** [comment]
I can't get around to fixing it this week, but I would be happy to accept a pull request.

**Comment by clayrisser** [comment]
This should be supported now in `0.2.0`. I also added typescript support.
